// frontend/src/components/Register.vue
<script setup lang="ts">
import { reactive, ref } from 'vue';
import services from '../Services';
import Input from './Input.vue';

const userData = reactive({
    email: ref(''),
    password: ref(''),
    confirmPassword: ref(''),
})

async function submit() {
    if(userData.password != userData.confirmPassword) {
        alert('As senhas devem ser idênticas!')
        return
    }
    await services.createAccount(userData.email, userData.password)
}

</script>

<template>
    <div>
        <div class="w-full h-full">
            <Input class="mb-4" type="email" v-model="userData.email" placeholder="email"/>
            <Input class="mb-4" type="password" v-model="userData.password" placeholder="senha"/>
            <Input class="mb-4" type="password" v-model="userData.confirmPassword" placeholder="confirme sua senha"/>
            <button class="block m-auto text text-pri-100 bg-pri-400 py-3 px-6 rounded-full font-bold" @click="submit">
                Criar conta
            </button>
        </div>
    </div>
</template>

// frontend-react/src/components/Register.tsx
import { ChangeEvent, FormEvent, useState } from "react";
import VCenteredCnt from "./containers/VCenteredCnt";

export default function Register() {

    interface i_userData {
        // nickname: string;
        // name: string;
        email: string;
        password: string;
        checkpass: string;
    }

    const [userData, setUserData] = useState<i_userData>({
        // nickname: '',
        // name: '',
        email: '',
        password: '',
        checkpass: '',
    });

    const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
        e.preventDefault()
        setUserData({ ...userData, [e.target.name]: e.target.value })
    }

    const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        if(userData.password != userData.checkpass) {
            alert('As senhas devem ser idênticas!')
            return
        }
        
    }

    const inputStyle = 'bg-pri-300 text-pri-600 placeholder-pri-600 font-bold my-1 h-10 text-center rounded-3xl focus:scale-110 transition-all'
    return(
        <VCenteredCnt>
            <div>
                <form onSubmit={handleSubmit} autoComplete="false" className="flex flex-col w-[96%] max-w-md" aria-readonly>
                    <input autoComplete="off" className={inputStyle} type="email" onChange={handleChange} name="email" placeholder='example@mail.com'/>
                    <input autoComplete="off" className={inputStyle} type="password" onChange={handleChange} name="password" placeholder='******'/>
                    <input autoComplete="off" className={inputStyle} type="password" onChange={handleChange} name="checkpass" placeholder='confirme sua senha'/>
                    <input className="bg-pri-500 text-pri-200 font-extrabold h-10 text-center rounded-3xl m-auto" type="submit" value="Criar conta"/>
                </form> 
            </div>
        </VCenteredCnt>
    )
}
