// frontend/src/App.vue
<script setup lang="ts">
import { onBeforeMount } from 'vue';
import { RouterView } from 'vue-router';
import Header from './components/Header.vue';
import LoginPopup from './components/LoginPopup.vue';
import NavBar from './components/NavBar.vue';
import services from './Services';
import { homePagePosts } from './Store';

onBeforeMount(async () => {
  homePagePosts.value = await services.getPosts()
})
</script>

<template>
  <div class="fixed w-full h-full md:max-w-lg md:resize-x">
    <LoginPopup/>
    <div class="h-full w-full flex flex-col items-center">
      <Header/>
      <div class="h-full w-full flex-grow overflow-auto text-md">
        <RouterView></RouterView>
      </div>
      <NavBar/>
    </div>
  </div>
</template>

// frontend-react/src/App.tsx
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom'
import Home from './components/Home';
import Header from './components/Header';
import Navbar from './components/Navbar';
import services from './Services';
import { useContext } from 'react';
import { userContext } from './contexts/UserProvider';

function App() {
  const [user, setUser] = useContext(userContext)
  services.onAuthStateChange(() => setUser(services.getCurrentUser()))
  
  return (
    <div className="App m-auto h-full max-h-full fixed w-full bg-pri-50 text-black text-center overflow-y-auto">
      <Header/>
      <Router>
          <Routes>
            <Route path='/' element={<Home/>}/>
          </Routes>
        <Navbar/>
      </Router>
    </div>
  )
}

export default App
